.PHONY: clean All

All:
	@echo "----------Building project:[ builder_pattern - Debug ]----------"
	@cd "builder_pattern" && "$(MAKE)" -f  "builder_pattern.mk"
clean:
	@echo "----------Cleaning project:[ builder_pattern - Debug ]----------"
	@cd "builder_pattern" && "$(MAKE)" -f  "builder_pattern.mk" clean
