.PHONY: clean All

All:
	@echo "----------Building project:[ p1 - Debug ]----------"
	@cd "p1" && "$(MAKE)" -f  "p1.mk"
clean:
	@echo "----------Cleaning project:[ p1 - Debug ]----------"
	@cd "p1" && "$(MAKE)" -f  "p1.mk" clean
